### ISSUE TITLE
Understanding~ Integration Review: 2-What InnerSource~

### ISSUE THREAD

**Issue by masskaneko** [InnerSourceCommons/japanese-contents#80]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/2-what-innersource-is-and-isnt.md?plain=1

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/2-what-innersource-is-and-isnt.md?plain=1#L14

痛手は→問題は

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/2-what-innersource-is-and-isnt.md?plain=1#L65

これ、やはり「重役」は「お偉いさん」とかにできませんかね？
「お偉いさん」がびみょうなら「役職者」とか
それか、そもそも Big Cheese Story をそのまま訳さずに、「役職者が協働を阻むお話し」とかにしちゃうとか...

重役と聞くと、社内組織の誰かを指す感覚がなく、以下の意味が先に思い付きます。
- 責任の重い役目・役職。大役 (たいやく) 。「―を仰せつかる」

ここから文脈からして誰かのことを指すのではなくもう少し抽象的な概念なのかと思い読み始めてしまいます。
もしくは、重役と聞くと、むしろ「会長・社長・専務・常務その他、取締り役」のような本当に上の役員まで上がってしまい、
これが役員でない VPoE の可能性や、そのた役員でない部長や大きな組織における権力の強い課長のようなものは Big Cheese にそもそも含まれない感じがしてしまいます。
巨大な組織だと、そんな役員の人が個々のプロジェクトに口を出したり、その人にエスカレーションが発生したりすることはほぼない気がします。
重役をそういった偉い(一番偉い)人たちのことだと思った人は「彼女のレポートラインにいる重役はとても喜び」という表現が誰のことを指しているのか不透明になってしまう気がします。

なので、違和感を感じました... 私だけでしょうか...

ちょっと他のレビュワーの皆様の意見も聞いてみたいです。
@bory-kb @Mura-Mi @amixedcolor @ystk @hiromotai7 @shrimp78

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/2-what-innersource-is-and-isnt.md?plain=1#L149

ユーザーストーリーって、アジャイル開発のプロダクトバックログを「ユーザーストーリー」という形で表現する。あのユーザーストーリーですよね

英語で stories だけで出てきたときに、（事の）経緯，展開　という意味も持ちそうです。
ここでは「ユーザーストーリー」とスコープを狭めずに、「ことの経緯」とか他の言葉にした方がいいかもと思いました。
ここではあえて "user stories" と書かれていない気もするので、アジャイルやスクラムの手法論的な "User Story" ではなく もっと一般的な手稿の意味の "story" なのかなと思いました。

しかし、「バックログに溜まっていた他チームからのストーリーも解消したのです。」とあるので、まあこれは "ユーザーストーリー" のことを指しているとも理解できそうです。

たぶん「ユーザーストーリー」で良いと思いますが、だとしたらなんで、用語のユーザーストーリーのほうを翻訳元は書いていないのか気になりました

**Comment by masskaneko** [comment]
思い出しました。big cheese 自体は "お偉いさん" と最初考えたんですよ。
ですが、big cheese story というと "＊＊物語" が複合語らしくなる (例：指輪物語) と考えて、
"お偉いさん物語" だと語呂がよくないなぁと感じて、じゃあ "重役物語" かなぁと。
でも改めて考えると @yuhattor の言うように

> そんな役員の人が個々のプロジェクトに口を出したり、その人にエスカレーションが発生したりすることはほぼない

というのはその通りに思えて "重役物語" はいかんかなと思い始めたところです。

**Comment by masskaneko** [comment]
文脈からして stories は間違いなく user stories (スクラムで言うプロダクトバックログアイテム) だと思います。
ストーリーと書くと曖昧なのでユーザーストーリーと明示しました。
著者は単に stories と略すくせがあるのでは。
