### ISSUE TITLE
Understanding~ Integration Review: 6-Working within the Enterprise~

### ISSUE THREAD

**Issue by masskaneko** [InnerSourceCommons/japanese-contents#84]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/6-working-within-the-enterprise-understanding-planning.md?plain=1

**Comment by yuhattor** [comment]
私もどれが正しい日本語なのかわかってないのですが、

https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/6-working-within-the-enterprise-understanding-planning.md?plain=1#L11

目線を持つは普通でしょうか？検索したら「目線を持つ」表現も出てきました

が、個人的に良いと思う（好きで使っている?）のは
同じ目線に立つ / 同じ視点を持つの組み合わせです
どちらがよいでしょう。

また、他の候補としては、たんに「共通認識を持つ」に変えてしまうのも良いかもしれません

**Comment by yuhattor** [comment]
細かいですが

https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/6-working-within-the-enterprise-understanding-planning.md?plain=1#L13

マネジメント/マネージメント

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/6-working-within-the-enterprise-understanding-planning.md?plain=1#L14

Open Collaboration の訳です。
開かれたコラボレーション
とかでも良いかなと思いました。どうでしょう

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/6-working-within-the-enterprise-understanding-planning.md?plain=1#L56

ポジティブなフィードバック
「な」を入れたいなと思いました

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/6-working-within-the-enterprise-understanding-planning.md?plain=1#L72

プロダクトではなく製品と訳していることから、ここはフィーチャーでなく機能とやくしてもいいかもしれません

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/6-working-within-the-enterprise-understanding-planning.md?plain=1#L142

名詞の「ファシリテーションが必要」ですかね
それか、日本語にして「促進」とかにしちゃいます？
ファシリテーションは訳しにくいのでそのままでもいいかもしれません
