### ISSUE TITLE
Understanding~ Integration Review: 7-From Internal Silos to~

### ISSUE THREAD

**Issue by masskaneko** [InnerSourceCommons/japanese-contents#85]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/7-from-internal-silos-to-internal-transparency.md?plain=1

**Comment by yuhattor** [comment]
TL;DR はなに調にするのがいいですかね

https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/7-from-internal-silos-to-internal-transparency.md?plain=1#L10-L11

ここでは「だである調」になってます
#68 に追記します

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/7-from-internal-silos-to-internal-transparency.md?plain=1#L72

documentation はドキュメンテーション
に統一してもいいかもです

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/7-from-internal-silos-to-internal-transparency.md?plain=1#L103-L104

発見容易性 / 発見可能性 / 検索可能性
どちらかに統一したいと思いました。
発見容易性も良いですね。Find+able なので、可能性という訳のほうが直接的ですが、
Discoverable とも被ります。検索可能は Searchable とも被ります

どうしましょうかね。"発見可能性"は Google 検索で 299,000 件みつかりますが、"発見容易性" は 266 件であるため、メジャーな表現ではなさそうです。

参考の考察は以下でしてます。
https://github.com/InnerSourceCommons/jp-contents/pull/72#discussion_r1066722711

みなさんのコメントいただきたいです

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/7-from-internal-silos-to-internal-transparency.md?plain=1#L116

ゆく / いく
これもとういつしたいなと

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/7-from-internal-silos-to-internal-transparency.md?plain=1#L133

コラボレーションを創出する優先度が高い**ことを**経営レベルで判断することも重要です。

どうでしょう
